ALTER TABLE TBL_TRANSACTION
ADD CONSTRAINT CHECK_AMOUNT CHECK(AMOUNT_NUMBER>-1000 AND AMOUNT_NUMBER<1000);

ALTER TABLE TBL_EMPLOYEE
ADD CONSTRAINT CHECK_MIDDLE_NAME CHECK
(REPLACE(EMPLOYEE_MIDDLE_NAME, '.', '') = EMPLOYEE_MIDDLE_NAME OR EMPLOYEE_MIDDLE_NAME IS NULL)
ENABLE NOVALIDATE;

ALTER TABLE TBL_EMPLOYEE
ADD CONSTRAINT CHECK_DATE_OF_BIRTH CHECK(EXTRACT(YEAR FROM DATE_OF_BIRTH) BETWEEN 1900 AND 2099)
ENABLE NOVALIDATE;