ALTER TABLE TBL_TRANSACTION
ADD (Date_of_Entry TIMESTAMP DEFAULT SYSDATE);

ALTER TABLE TBL_TRANSACTION
MODIFY (Date_of_Entry TIMESTAMP DEFAULT SYSDATE);

UPDATE TBL_TRANSACTION
SET Date_of_Entry = NULL;

SELECT * FROM tbl_transaction;

SELECT * FROM TBL_TRANSACTION
WHERE employee_number < 3;

ALTER TABLE TBL_TRANSACTION
MODIFY (Date_of_Entry TIMESTAMP DEFAULT ON NULL SYSDATE);

ROLLBACK;