SELECT COUNT(*) AS COUNT FROM TBL_TRANSACTION;

DELETE TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER IN
(SELECT T.EMPLOYEE_NUMBER
FROM 
    TBL_EMPLOYEE E RIGHT JOIN TBL_TRANSACTION T
    ON e.employee_number = t.employee_number
WHERE
    E.EMPLOYEE_NUMBER IS NULL);
    
SELECT COUNT(*) AS COUNT FROM TBL_TRANSACTION;

ROLLBACK; -- undo the changes
--COMMIT; -- save the changes