SELECT P.PRODUCT_ID 
FROM PTBL_PRODUCT P LEFT JOIN PTBL_TRANSACTION T
ON P.PRODUCT_ID = T.PRODUCT_ID
WHERE T.PRODUCT_ID IS NULL
ORDER BY P.PRODUCT_ID;

UPDATE PTBL_TRANSACTION
SET TRANSACTION_DATE = ADD_MONTHS(TRANSACTION_DATE, 120);
ROLLBACK;

DELETE PTBL_TRANSACTION
WHERE TRANSACTION_DATE = TO_DATE('31 July 2013', 'DD MM YYYY');
ROLLBACK;
