INSERT INTO VIEW_DEPARTMENT(employee_number, date_of_transaction, total_amount)
VALUES (132, TO_DATE('2015-7-07', 'YYYY-MM-DD'), 999.99);

ALTER TABLE TBL_DEPARTMENT
ADD CONSTRAINT PK_TBL_DEPARTMENT PRIMARY KEY(DEPARTMENT);

ROLLBACK;