CREATE OR REPLACE VIEW "VIEW_DEPARTMENT" AS 
SELECT D.DEPARTMENT, T.EMPLOYEE_NUMBER, T.DATE_OF_TRANSACTION, T.AMOUNT_NUMBER AS TOTAL_AMOUNT
FROM TBL_DEPARTMENT D
LEFT JOIN TBL_EMPLOYEE E ON D.DEPARTMENT = E.DEPARTMENT
LEFT JOIN TBL_TRANSACTION T ON E.EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER
WHERE T.EMPLOYEE_NUMBER BETWEEN 120 AND 139
ORDER BY D.DEPARTMENT, T.EMPLOYEE_NUMBER;

DROP VIEW VIEW_DEPARTMENT;

CREATE OR REPLACE VIEW "VIEW_DEPARTMENT" AS 
SELECT D.DEPARTMENT, T.EMPLOYEE_NUMBER, T.DATE_OF_TRANSACTION, T.AMOUNT_NUMBER AS TOTAL_AMOUNT
FROM TBL_DEPARTMENT D
LEFT JOIN TBL_EMPLOYEE E ON D.DEPARTMENT = E.DEPARTMENT
LEFT JOIN TBL_TRANSACTION T ON E.EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER
WHERE T.EMPLOYEE_NUMBER BETWEEN 120 AND 139
ORDER BY D.DEPARTMENT, T.EMPLOYEE_NUMBER
WITH READ ONLY; -- VIEWER CAN'T ADD ANY ROWS

ROLLBACK;

CREATE OR REPLACE VIEW "VIEW_DEPARTMENT" AS 
SELECT D.DEPARTMENT, T.EMPLOYEE_NUMBER, T.DATE_OF_TRANSACTION, T.AMOUNT_NUMBER AS TOTAL_AMOUNT
FROM TBL_TRANSACTION T
WHERE T.EMPLOYEE_NUMBER BETWEEN 120 AND 139
WITH CHECK OPTION CONSTRAINT Constraint_View_Department;

