CREATE VIEW VIEW_DEPARTMENT AS
SELECT D.DEPARTMENT, T.EMPLOYEE_NUMBER, T.DATE_OF_TRANSACTION, T.AMOUNT_NUMBER AS TOTAL_AMOUNT
FROM TBL_DEPARTMENT D
LEFT JOIN TBL_EMPLOYEE E ON D.DEPARTMENT = E.DEPARTMENT
LEFT JOIN TBL_TRANSACTION T ON E.EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER
WHERE T.EMPLOYEE_NUMBER BETWEEN 120 AND 139
ORDER BY D.DEPARTMENT, T.EMPLOYEE_NUMBER;

SELECT * FROM VIEW_DEPARTMENT;
SELECT * FROM VIEW_SUMMARY;

CREATE VIEW VIEW_SUMMARY AS
SELECT D.DEPARTMENT, T.EMPLOYEE_NUMBER, SUM(T.AMOUNT_NUMBER) AS TOTAL_AMOUNT
FROM TBL_DEPARTMENT D
LEFT JOIN TBL_EMPLOYEE E ON D.DEPARTMENT = E.DEPARTMENT
LEFT JOIN TBL_TRANSACTION T ON E.EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER
GROUP BY D.DEPARTMENT, T.EMPLOYEE_NUMBER
ORDER BY D.DEPARTMENT, T.EMPLOYEE_NUMBER;
