SELECT EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE,
    ROUND(CUME_DIST() OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH), 4) AS CUME_DIST,
    ROUND(PERCENT_RANK() OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH), 4) AS PERCENT_RANK,
    ROUND(CUME_DIST() OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) * COUNT(*) OVER(PARTITION BY EMPLOYEE_NUMBER), 4) AS CUME_DIST_HEHE,
    ROUND(PERCENT_RANK() OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) * (COUNT(*) OVER(PARTITION BY EMPLOYEE_NUMBER) - 1), 4) AS PERCENT_RANK_HEHE
FROM TBL_ATTENDANCE;

SELECT EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE,
    ROUND(CUME_DIST() OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) * 44, 4) AS CUME_DIST,
    ROUND(PERCENT_RANK() OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) * 43, 4) AS PERCENT_RANK
FROM (SELECT * FROM TBL_ATTENDANCE UNION ALL SELECT * FROM TBL_ATTENDANCE); -- SIMILAR ROWS 