SELECT EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE,
    FIRST_VALUE(NUMBER_ATTENDANCE) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH
    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS FIRST_MONTH,
    LAST_VALUE(NUMBER_ATTENDANCE) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_MONTH
FROM TBL_ATTENDANCE;