CREATE TABLE TBL_TRANSACTION_NEW(
AMOUNT NUMBER(15,2)
, DATE_OF_TRANSACTION DATE
, EMPLOYEE_NUMBER NUMBER(4,0)
, DATE_OF_ENTRY TIMESTAMP(6) DEFAULT ON NULL SYSDATE
, SHOULD_I_DELETE NUMBER(1,0)
);

INSERT INTO TBL_TRANSACTION_NEW
SELECT AMOUNT_NUMBER, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER, DATE_OF_ENTRY, MOD(ROWNUM, 3) AS SHOULD_I_DELETE
FROM TBL_TRANSACTION;

SELECT * FROM TBL_TRANSACTION_NEW;

DELETE FROM TBL_TRANSACTION_NEW
WHERE SHOULD_I_DELETE = 1;

UPDATE TBL_TRANSACTION_NEW
SET DATE_OF_TRANSACTION = DATE_OF_TRANSACTION + 1
WHERE SHOULD_I_DELETE = 2;

SELECT AMOUNT_NUMBER, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER FROM TBL_TRANSACTION
MINUS
SELECT AMOUNT, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER FROM TBL_TRANSACTION_NEW
ORDER BY EMPLOYEE_NUMBER;

SELECT AMOUNT_NUMBER, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER FROM TBL_TRANSACTION WHERE EMPLOYEE_NUMBER = 1
INTERSECT
SELECT AMOUNT, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER FROM TBL_TRANSACTION_NEW WHERE EMPLOYEE_NUMBER = 1;

SELECT AMOUNT_NUMBER, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER FROM TBL_TRANSACTION WHERE EMPLOYEE_NUMBER = 1
MINUS
SELECT AMOUNT, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER FROM TBL_TRANSACTION_NEW WHERE EMPLOYEE_NUMBER = 1;