SELECT EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE,
    LAG(NUMBER_ATTENDANCE, 1) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS MY_LAG,
    NUMBER_ATTENDANCE - LAG(NUMBER_ATTENDANCE, 1) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS MY_LAG_DIFF,
    LEAD(NUMBER_ATTENDANCE, 1) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS MY_LEAD,
    FIRST_VALUE(NUMBER_ATTENDANCE) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH
    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS FIRST_MONTH,
    LAST_VALUE(NUMBER_ATTENDANCE) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_MONTH
FROM TBL_ATTENDANCE;