MERGE INTO TBL_TRANSACTION T
USING TBL_TRANSACTION_NEW S
ON (T.EMPLOYEE_NUMBER = S.EMPLOYEE_NUMBER AND T.DATE_OF_TRANSACTION = S.DATE_OF_TRANSACTION)
WHEN MATCHED THEN UPDATE SET AMOUNT_NUMBER = T.AMOUNT_NUMBER + S.AMOUNT
, COMMENTS = CASE WHEN S.AMOUNT > 0 THEN 'UPDATED ROW - POSITIVE' ELSE 'UPDATED ROW - NEGATIVE' END
WHERE S.AMOUNT > 0
DELETE WHERE  S.AMOUNT < 100
WHEN NOT MATCHED THEN   INSERT(AMOUNT_NUMBER, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER, COMMENTS)
                        VALUES(S.AMOUNT, S.DATE_OF_TRANSACTION, S.EMPLOYEE_NUMBER, 'INSERTED ROW');
                        -- I GOT ERROR :/
                        
ALTER TABLE TBL_TRANSACTION
ADD COMMENTS NVARCHAR2(50) NULL;