SELECT DISTINCT EMPLOYEE_NUMBER,
PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY NUMBER_ATTENDANCE) OVER(PARTITION BY EMPLOYEE_NUMBER) AS MY_PERCENTILE_COUNT,
PERCENTILE_DISC(0.5) WITHIN GROUP(ORDER BY NUMBER_ATTENDANCE) OVER(PARTITION BY EMPLOYEE_NUMBER) AS MY_PERCENTILE_DISC
FROM TBL_ATTENDANCE
ORDER BY EMPLOYEE_NUMBER;