MERGE INTO PTBL_SUBCATEGORY T 
USING PTBL_SUBCATEGORY_NEW S
ON (T.PRODUCT_SUBCATEGORY_ID = S.PRODUCT_SUBCATEGORY_ID) 
WHEN MATCHED THEN UPDATE SET PRODUCT_CATEGORY_ID = S.PRODUCT_CATEGORY_ID,
                             SUBCATEGORY_NAME = S.SUBCATEGORY_NAME
WHEN NOT MATCHED THEN INSERT (PRODUCT_SUBCATEGORY_ID, PRODUCT_CATEGORY_ID, SUBCATEGORY_NAME)
                        VALUES(S.PRODUCT_SUBCATEGORY_ID, S.PRODUCT_CATEGORY_ID, S.SUBCATEGORY_NAME);
                        


SELECT * FROM PTBL_SUBCATEGORY;

ROLLBACK;
                        