SELECT TRANSACTION_DATE, ACTUAL_COST, SUM(ACTUAL_COST)
    OVER( ORDER BY TRANSACTION_DATE 
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ACTUAL_COST_TO_DATE,
    SUM(ACTUAL_COST)
    OVER(PARTITION BY TO_CHAR(TRANSACTION_DATE, 'YYMM')
    ORDER BY TRANSACTION_DATE 
    ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS TOTAL_COST_PER_MONTH
FROM PTBL_TRANSACTION
ORDER BY TRANSACTION_DATE;