SELECT EMPLOYEE_NUMBER, TO_CHAR(ATTENDANCE_MONTH, 'YYY-MM') AS ATTENDACE, NUMBER_ATTENDANCE, ROWNUM AS PSUEDOCOLUMN
    , ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS THE_ROW_NUMBER
    , RANK() OVER (PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS THE_RANK
    , ROW_NUMBER() OVER (ORDER BY NULL) AS THE_ROW_NUMBER_WITH_NULL

FROM(   SELECT * FROM TBL_ATTENDANCE
        UNION ALL
        SELECT * FROM TBL_ATTENDANCE);


SELECT EMPLOYEE_NUMBER, TO_CHAR(ATTENDANCE_MONTH, 'YYY-MM') AS ATTENDACE, NUMBER_ATTENDANCE
    , ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS THE_ROW_NUMBER
    , NTILE(10) OVER(PARTITION BY EMPLOYEE_NUMBER ORDER BY ATTENDANCE_MONTH) AS THE_NTILE
FROM TBL_ATTENDANCE
WHERE ATTENDANCE_MONTH < TO_DATE('22-05-01', 'YY-MM-DD');