SELECT CAST('JOKER' AS VARCHAR2(11)) || '.'
FROM DUAL
UNION -- ALL 
SELECT CAST('MY' AS VARCHAR2(11)) || '.'
FROM DUAL
UNION -- ALL 
SELECT CAST('NAME' AS VARCHAR2(11)) || '.'
FROM DUAL
UNION -- ALL 
SELECT CAST('IS' AS VARCHAR2(11)) || '.'
FROM DUAL
UNION -- ALL 
SELECT CAST('JOKER' AS VARCHAR2(11)) || '.'
FROM DUAL;

SELECT CAST(45 AS NUMBER(2, 0))
FROM DUAL
UNION ALL 
SELECT CAST(456.78 AS NUMBER(6, 3))
FROM DUAL;

SELECT CAST(TO_DATE('22-01-2002', 'DD-MM-YYYY') AS DATE)
FROM DUAL
UNION ALL 
SELECT CAST(TO_DATE('03-04-2000', 'DD-MM-YYYY') AS TIMESTAMP)
FROM DUAL;