DROP TABLE RISHI;

CREATE TABLE RISHI(
NAME NVARCHAR2(50) NOT NULL
,MIDNAME NVARCHAR2(50) NULL
,LASTNAME NVARCHAR2(50) NOT NULL
,ROLL_NO DECIMAL(6, 0) NOT NULL
);

ALTER TABLE RISHI
ADD DATE_OF_BIRTH TIMESTAMP NULL;

ALTER TABLE RISHI
MODIFY DATE_OF_BIRTH DATE NOT NULL;

ALTER TABLE RISHI
DROP COLUMN DATE_OF_BIRTH;

INSERT INTO RISHI
VALUES ('RISHI', 'K.', 'PATIL', '1001', '22/JANUARY/2002');

SELECT * 
FROM RISHI;

TRUNCATE TABLE RISHI;