SELECT * FROM TBL_EMPLOYEE
WHERE EMPLOYEE_NUMBER LIKE 200; -- EQUAL TO 200

SELECT * FROM TBL_EMPLOYEE
WHERE EMPLOYEE_NUMBER NOT LIKE 200; -- NOT EQUAL TO 200 LIKE <> != ^=

SELECT * FROM TBL_EMPLOYEE
WHERE employee_number BETWEEN 200 AND 209;

SELECT * FROM TBL_EMPLOYEE
WHERE NOT(EMPLOYEE_NUMBER >= 200) AND EMPLOYEE_NUMBER <= 209; -- COMBINE 2 CONDITIONS

SELECT * FROM TBL_EMPLOYEE
WHERE EMPLOYEE_NUMBER >= 200 OR NOT(EMPLOYEE_NUMBER <= 209); 

SELECT * FROM TBL_EMPLOYEE
WHERE EMPLOYEE_NUMBER IN(200, 204, 209, 210); 

SELECT * FROM TBL_EMPLOYEE
WHERE EXTRACT(YEAR FROM DATE_OF_BIRTH) BETWEEN 1970 AND 1980; -- DO NOT USE

SELECT * FROM TBL_EMPLOYEE
WHERE DATE_OF_BIRTH >= TO_DATE('1970-01-01', 'YYYY-MM-DD') AND DATE_OF_BIRTH <= TO_DATE('1980-01-01', 'YYYY-MM-DD');  -- BETTER