CREATE TABLE TBL_DEPARTMENT AS(
    SELECT DEPARTMENT FROM(
        SELECT DEPARTMENT, COUNT(*)
        FROM tbl_employee
        GROUP BY DEPARTMENT
    )
);

SELECT * FROM tbl_department;

ALTER TABLE TBL_DEPARTMENT
ADD DEPARTMENT_HEAD VARCHAR2(20 CHAR);