SELECT DEPARTMENT_HEAD, SUM(AMOUNT_NUMBER) AS TOTAL_AMOUNT
FROM TBL_DEPARTMENT LEFT JOIN TBL_EMPLOYEE
USING(DEPARTMENT) LEFT JOIN TBL_TRANSACTION
USING(EMPLOYEE_NUMBER)
GROUP BY DEPARTMENT_HEAD
ORDER BY DEPARTMENT_HEAD;

TRUNCATE TABLE TBL_DEPARTMENT;
INSERT INTO TBL_DEPARTMENT VALUES('Customer Relations', 'Ritik');
INSERT INTO TBL_DEPARTMENT VALUES('HR', 'Rani');
INSERT INTO TBL_DEPARTMENT VALUES('Commercial', 'Rishi');
INSERT INTO TBL_DEPARTMENT VALUES('Accounts', 'Krishna');
INSERT INTO TBL_DEPARTMENT VALUES('Litigation', 'Rishi');