CREATE OR REPLACE DIRECTORY EXT_TAB_DIR AS 'M:\SQL';
GRANT READ ON DIRECTORY EXT_TAB_DIR TO SYS;

CREATE TABLE EMP_LOAD(FIRST_NAME CHAR(15), LAST_NAME CHAR(20), YEAR_OF_BIRTH INT)
 ORGANIZATION EXTERNAL  (TYPE ORACLE_LOADER
                        DEFAULT DIRECTORY EXT_TAB_DIR
                        ACCESS PARAMETERS
                        (FIELDS TERMINATED BY "|")
                        LOCATION('INFO.DAT'));
                        
SELECT * FROM EMP_LOAD;
DROP TABLE EMP_LOAD;

CREATE TABLE EMP_LOAD(FIRST_NAME CHAR(15), LAST_NAME CHAR(20), YEAR_OF_BIRTH INT)
 ORGANIZATION EXTERNAL  (TYPE ORACLE_LOADER
                        DEFAULT DIRECTORY EXT_TAB_DIR
                        ACCESS PARAMETERS
                        (FIELDS TERMINATED BY "\t" OPTIONALLY ENCLOSED BY '""')
                        LOCATION('INFO.DAT')); --> WHEN FIELDS ARE TERMINATED BY SPACE ONLY

SELECT * FROM EMP_LOAD;
DROP TABLE EMP_LOAD;                       
                        
CREATE TABLE EMP_LOAD(FIRST_NAME CHAR(15), LAST_NAME CHAR(20), YEAR_OF_BIRTH INT)
 ORGANIZATION EXTERNAL  (TYPE ORACLE_LOADER
                        DEFAULT DIRECTORY EXT_TAB_DIR
                        ACCESS PARAMETERS
                        (FIELDS CSV  WITHOUT EMBEDDED RECORD TERMINATORS)
                        LOCATION('INFO.DAT')); --> SEPARATED BY ','