CONNECT C##RISHI/Rishi123
CREATE TABLE C##RISHI.TBL_ATTENDANCE_RISHI
("EMPLOYEE_NUMBER" NUMBER(4,0), 
"ATTENDANCE_MONTH" TIMESTAMP (6), 
"NUMBER_ATTENDANCE" NUMBER(4,0),
CONSTRAINT "PK_ATTENDANCE" PRIMARY KEY ("EMPLOYEE_NUMBER", "ATTENDANCE_MONTH"));

CONNECT C##RISHI/Rishi123
ALTER TABLE C##RISHI.TBL_ATTENDANCE_RISHI ENABLE ROW MOVEMENT;

CONNECT C##RISHI/Rishi123
SELECT * FROM C##RISHI.TBL_ATTENDANCE_RISHI
ORDER BY EMPLOYEE_NUMBER DESC, ATTENDANCE_MONTH;

CONNECT C##RISHI/Rishi123
INSERT INTO C##RISHI.TBL_ATTENDANCE_RISHI (EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE)
VALUES (200, TO_DATE('2022-01-01', 'YYYY-MM-DD'), 14);
CONNECT C##RISHI/Rishi123
INSERT INTO C##RISHI.TBL_ATTENDANCE_RISHI (EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE)
VALUES (201, TO_DATE('2022-01-01', 'YYYY-MM-DD'), 15);
CONNECT C##RISHI/Rishi123
INSERT INTO C##RISHI.TBL_ATTENDANCE_RISHI (EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE)
VALUES (202, TO_DATE('2022-01-01', 'YYYY-MM-DD'), 16);

CONNECT C##RISHI/Rishi123
FLASHBACK TABLE C##RISHI.TBL_ATTENDANCE_RISHI
TO TIMESTAMP(SYSTIMESTAMP - INTERVAL '5'MINUTE);

SELECT SYSTIMESTAMP - INTERVAL '1'MINUTE FROM DUAL;
SELECT TIMESTAMP_TO_SCN(SYSTIMESTAMP - INTERVAL '5'MINUTE) FROM DUAL;

TRUNCATE TABLE C##RISHI.TBL_ATTENDANCE_RISHI;

DROP TABLE C##RISHI.TBL_ATTENDANCE_RISHI;

FLASHBACK TABLE C##RISHI.TBL_ATTENDANCE_RISHI TO BEFORE DROP;