CREATE USER C##RISHI IDENTIFIED BY Rishi123;
ALTER USER C##RISHI IDENTIFIED BY Rishi123;
DROP USER C##RISHI CASCADE;

SELECT CDB FROM V$DATABASE;

CONNECT C##RISHI
GRANT CREATE SESSION TO C##RISHI;
GRANT UNLIMITED TABLESPACE TO C##RISHI;

CONNECT C##RISHI/Rishi123
SELECT USER FROM DUAL;

GRANT CONNECT, RESOURCE, DBA TO C##RISHI;
/* CONNECT INCLUDES THE FOLLOWING SYSTEM PRIVLILEGES -->
ALTER SESSION, CREATE CLUSTER, CREATE DATABASE LINK, CREATE SEQUENCE, CREATE SESSION, CREATE SYNONYM, CREATE TABLE, CREATE VIEW

RESOURCE INCLUDES THE FOLLOWING SYSTEM PRIVLILEGES -->
CREATE CLUSTER, CREATE INDEXTYPE, CREATE OPERATOR, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE

ALL SYSTEM PRIVILEGES WITH ADMIN OPTION -->
ORACLE CORPORATION RECOMMENDS THAT YOU DESIGN YOUR OWN ROLES FOR DATABASE SECURITY, EATHER THAN RELYING ON THESE ROLES.*/

GRANT CREATE ANY TABLE TO C##RISHI;
REVOKE RESOURCE FROM C##RISHI;
GRANT CREATE ANY TABLE TO PUBLIC; --> ALL USER
REVOKE CREATE ANY TABLE FROM PUBLIC;
GRANT CREATE ANY TABLE TO C##RISHI WITH ADMIN OPTION;

GRANT SELECT ON SYS.TBL_EMPLOYEE TO C##RISHI;

CREATE ROLE C##NEW_ROLE; --INDENTIFIED BY PASSWORD NEW123;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.TBL_ATTENDANCE TO C##NEW_ROLE;
GRANT C##NEW_ROLE TO C##RISHI;

SHOW USER