DROP INDEX IDX_TBL_TRANSACTION;
CREATE INDEX IDX_TBL_TRANSACTION ON TBL_TRANSACTION(AMOUNT_NUMBER); --> NON-UNIQUE INDEX
DROP INDEX IDX_TBL_ATTENDANCE;
CREATE UNIQUE INDEX IDX_TBL_ATTENDANCE ON TBL_ATTENDANCE(EMPLOYEE_NUMBER, ATTENDANCE_MONTH, NUMBER_ATTENDANCE); --> UNIQUE INDEX
DROP INDEX IDX_TBL_ATTENDANCE2;
CREATE UNIQUE INDEX IDX_TBL_ATTENDANCE2 ON TBL_ATTENDANCE(ATTENDANCE_MONTH, EMPLOYEE_NUMBER, NUMBER_ATTENDANCE);

ALTER INDEX IDX_TBL_ATTENDANCE UNUSABLE; -->PAUSE INDEX
ALTER INDEX IDX_TBL_ATTENDANCE REBUILD; --> PLAY INDEX

SELECT O.NAME, I.* FROM IND$ I LEFT JOIN OBJ$ O ON I.OBJ# = O.OBJ# ORDER BY O.NAME;