DROP TABLE MY_TEST_TABLE;
CREATE TABLE MY_TEST_TABLE(
MY_INTERVAL INTERVAL YEAR(5) TO MONTH);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '123-11' YEAR(3) TO MONTH);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '3-5' YEAR(3) TO MONTH);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '-3-5' YEAR(3) TO MONTH);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '13' YEAR);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '50' MONTH);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '2023' YEAR); --> ERROR

SELECT * FROM MY_TEST_TABLE;

DROP TABLE MY_TEST_TABLE;
CREATE TABLE MY_TEST_TABLE(
MY_INTERVAL INTERVAL DAY(3) TO SECOND(6));
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '1 2:3:4.567' DAY(3) TO SECOND(3));
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '3 4:5' DAY TO MINUTE);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '400 1' DAY(3) TO HOUR);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '2:3:4.567' HOUR TO SECOND(5));
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '-70' HOUR);
INSERT INTO MY_TEST_TABLE VALUES(INTERVAL '120' MINUTE);