SELECT * FROM TBL_EMPLOYEE;

CREATE TABLE TBL_EMPLOYEETEAM1 AS
SELECT * FROM TBL_EMPLOYEE WHERE 1=0;
CREATE TABLE TBL_EMPLOYEETEAM2 AS
SELECT * FROM TBL_EMPLOYEE WHERE 1=0; --> BLANK TABLE, THANKS TO WHERE STATEMENT!!

SELECT * FROM TBL_EMPLOYEETEAM1;
SELECT * FROM TBL_EMPLOYEETEAM2;

INSERT ALL 
INTO TBL_EMPLOYEETEAM1
INTO TBL_EMPLOYEETEAM2
SELECT * FROM TBL_EMPLOYEE;

TRUNCATE TABLE TBL_EMPLOYEETEAM1;
TRUNCATE TABLE TBL_EMPLOYEETEAM2;

INSERT ALL
INTO TBL_EMPLOYEETEAM1 VALUES(EMPLOYEE_NUMBER, EMPLOYEE_FIRST_NAME, EMPLOYEE_MIDDLE_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_GOVERNMENT_ID, DATE_OF_BIRTH, DEPARTMENT, MANAGER)
INTO TBL_EMPLOYEETEAM2 VALUES(EMPLOYEE_NUMBER, EMPLOYEE_FIRST_NAME, EMPLOYEE_MIDDLE_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_GOVERNMENT_ID, DATE_OF_BIRTH, DEPARTMENT, MANAGER)
SELECT EMPLOYEE_NUMBER, EMPLOYEE_FIRST_NAME, EMPLOYEE_MIDDLE_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_GOVERNMENT_ID, DATE_OF_BIRTH, DEPARTMENT, MANAGER FROM TBL_EMPLOYEE;

INSERT ALL
WHEN MOD(EMPLOYEE_NUMBER, 3) = 0 THEN INTO TBL_EMPLOYEETEAM1
WHEN MOD(EMPLOYEE_NUMBER, 4) = 0 THEN INTO TBL_EMPLOYEETEAM2
SELECT * FROM TBL_EMPLOYEE;

INSERT FIRST
WHEN MOD(EMPLOYEE_NUMBER, 3) = 0 THEN INTO TBL_EMPLOYEETEAM1
WHEN MOD(EMPLOYEE_NUMBER, 4) = 0 THEN INTO TBL_EMPLOYEETEAM2
SELECT * FROM TBL_EMPLOYEE;

SELECT * FROM TBL_EMPLOYEETEAM1
INTERSECT
SELECT * FROM TBL_EMPLOYEETEAM2;