/* SCHEMA NAMESPACES -->
YOU CAN ONLY NAME ONE TABLE, YOU CAN'T NAME THE SAME NAME TO OTHER TABLE
TABLES, VIEWS, SEQUENCES, --> SQL
PRIVATE SYNONYMS, STAND-ALONE PROCEDURES, STAND-ALONE STORED FUNCTIONS, PACKAGES, MATERIALIZED VIEWS, USER-DEFINED TYPES --> PL SQL

NAMESPACE -->
INDEXES, CONSTRAINTS --> SQL */

CONNECT C##RISHI/Rishi123
CREATE TABLE C##RISHI.TBL_EMPLOYEE
(MYFIELD VARCHAR2(20));

SELECT * FROM C##RISHI.TBL_EMPLOYEE;

DROP USER C##RISHI CASCADE;