DROP SEQUENCE NEWSEQ;
CREATE SEQUENCE NEWSEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 50;

SELECT NEWSEQ.NEXTVAL AS NEXTVALUE FROM DUAL;
SELECT NEWSEQ.CURRVAL AS NEXTVALUE FROM DUAL;

DROP TABLE TBL_TRANSACTION2;
CREATE TABLE TBL_TRANSACTION2(
AMOUNT NUMBER(15, 2) NOT NULL,
DATE_OF_TRANSACTION DATE,
EMPLOYEE_NUMBER NUMBER(10,0) NOT NULL,
NEXTNUMBER NUMBER(7,0) DEFAULT NEWSEQ.NEXTVAL);

DELETE FROM TBL_TRANSACTION2 WHERE NEXTNUMBER IS NULL;
SELECT * FROM TBL_TRANSACTION2;

INSERT INTO TBL_TRANSACTION2(AMOUNT, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER) VALUES (1, DATE '2017-01-01', 123);
INSERT INTO TBL_TRANSACTION2(AMOUNT, DATE_OF_TRANSACTION, EMPLOYEE_NUMBER, NEXTNUMBER) VALUES (1, DATE '2017-01-01', 123, NULL);

UPDATE TBL_TRANSACTION2 SET NEXTNUMBER = NEWSEQ.NEXTVAL WHERE NEXTNUMBER IS NULL;

ALTER SEQUENCE NEWSEQ INCREMENT BY 4 NOMINVALUE NOCACHE;