/* SYSTEM PRIVILEGE --> PERFORMING A DATABASE TASK
GRANT ____ TO USER;
REVOKE ____ FROM USER;
ALTER ANY
CREATE ANY(FOR ANY USER)
CREATE(FOR SPECIFIC USER)
CREATE SEQUENCE
DROP ANY
____ --> INDEX, ROLE, SEQUENCE, TABLE, VIEW

CREATE SESSION
INSERT ANY TABLE
SELECT ANY TABLE

OBJECT PRIVILEGE --> PERFORMING A TASK ON AN OBJECT
GRANT ____ ON OBJECT TO USER;
REVOKE ____ ON OBJECT FROM USER;
ALL(PRIVILEGES)
DELETE
INDEX
INSERT
REFERENCES
SELECT
UPDATE

ROLE --> A COLLECTION OF SYSTEM PRIVILEGES, OBJECT PRIVILEGES AND ROLES. */
