DROP SEQUENCE NEWSEQ;

CREATE SEQUENCE NEWSEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999
CYCLE
CACHE 50;

SELECT O.NAME, T.* FROM SYS.SEQ$ T LEFT JOIN OBJ$ O ON T.OBJ# = O.OBJ# ORDER BY O.NAME;