SELECT * FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER = ANY -- OR
    (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE
     WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER;

SELECT * FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER = SOME -- OR
    (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE
     WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER;

SELECT * FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER <> ALL -- AND
    (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE
     WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER; -- <> --> NOT EQUAL