SELECT RANK(15) WITHIN GROUP(ORDER BY NUMBER_ATTENDANCE) AS MY_RANK,
    DENSE_RANK(15) WITHIN GROUP(ORDER BY NUMBER_ATTENDANCE) AS MY_DENSE_RANK,
    PERCENT_RANK(15) WITHIN GROUP(ORDER BY NUMBER_ATTENDANCE) AS MY_PERCENT_RANK
FROM TBL_ATTENDANCE;