SELECT * FROM TBL_TRANSACTION
NATURAL LEFT JOIN TBL_EMPLOYEE
WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%'
ORDER BY EMPLOYEE_NUMBER; 

SELECT * FROM TBL_TRANSACTION
NATURAL LEFT JOIN (SELECT * FROM TBL_EMPLOYEE WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER;                                               ---|
                                                                            --|--> SAME
SELECT T.*, E.* FROM TBL_TRANSACTION T LEFT JOIN TBL_EMPLOYEE E         ---|
ON E.EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER AND UPPER(E.EMPLOYEE_LAST_NAME) LIKE 'Y%'
ORDER BY T.EMPLOYEE_NUMBER;  -- USE AND IN PLACE OF WHERE

-- DIFFERENCE WHEN YOU PUT LEFT JOIN