SELECT DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
      , GROUPING(ATTENDANCE_MONTH) AS IS_GROUPING_ATTENDANCE_MONTH
      , GROUPING_ID(DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH) AS THE_GROUPING_ID
FROM TBL_EMPLOYEE NATURAL JOIN TBL_ATTENDANCE
GROUP BY ROLLUP(DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH)
ORDER BY DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH;


SELECT DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
      , GROUPING(ATTENDANCE_MONTH) AS IS_GROUPING_ATTENDANCE_MONTH
      , GROUPING_ID(DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH) AS THE_GROUPING_ID
FROM TBL_EMPLOYEE NATURAL JOIN TBL_ATTENDANCE
GROUP BY CUBE(DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH)
ORDER BY DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH;


SELECT DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
      , GROUPING(ATTENDANCE_MONTH) AS IS_GROUPING_ATTENDANCE_MONTH
      , GROUPING_ID(DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH) AS THE_GROUPING_ID
FROM TBL_EMPLOYEE NATURAL JOIN TBL_ATTENDANCE
GROUP BY GROUPING SETS((DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH), (DEPARTMENT), (EMPLOYEE_NUMBER), ())
ORDER BY DEPARTMENT NULLS FIRST, EMPLOYEE_NUMBER NULLS FIRST, ATTENDANCE_MONTH NULLS FIRST;