SELECT DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
FROM TBL_EMPLOYEE JOIN TBL_ATTENDANCE USING(EMPLOYEE_NUMBER)
GROUP BY DEPARTMENT, EMPLOYEE_NUMBER, ATTENDANCE_MONTH
UNION

SELECT DEPARTMENT, EMPLOYEE_NUMBER, NULL, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
FROM TBL_EMPLOYEE JOIN TBL_ATTENDANCE USING(EMPLOYEE_NUMBER)
GROUP BY DEPARTMENT, EMPLOYEE_NUMBER
UNION

SELECT DEPARTMENT, NULL, NULL, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
FROM TBL_EMPLOYEE JOIN TBL_ATTENDANCE USING(EMPLOYEE_NUMBER)
GROUP BY DEPARTMENT
UNION

SELECT NULL, NULL, NULL, SUM(NUMBER_ATTENDANCE) AS NUMBER_ATTENDANCE
FROM TBL_EMPLOYEE JOIN TBL_ATTENDANCE USING(EMPLOYEE_NUMBER)
ORDER BY 1, 2, 3;