SELECT * FROM(
SELECT T.*, ROWNUM AS MY_ROWNUM FROM TBL_TRANSACTION T)
WHERE MY_ROWNUM = 3;


SELECT T.*, ROWNUM AS MY_ROW FROM TBL_TRANSACTION T
FETCH FIRST 3 ROWS ONLY;


SELECT T.*, ROWNUM AS MY_ROW FROM TBL_TRANSACTION T
--OFFSET 3 ROW FETCH FIRST 7 ROWS ONLY
OFFSET 3 ROW FETCH NEXT 7 ROWS ONLY;
 
 
SELECT * FROM(
SELECT T.*, ROWNUM AS MY_ROWNUM FROM TBL_TRANSACTION T)
WHERE MY_ROWNUM BETWEEN 3 AND 10;


SELECT EMPLOYEE_NUMBER FROM TBL_TRANSACTION
ORDER BY EMPLOYEE_NUMBER
OFFSET 2 ROWS FETCH NEXT 5 ROWS WITH TIES;