SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_SUBCATEGORY_ID
FROM PTBL_PRODUCT
WHERE PRODUCT_SUBCATEGORY_ID IN (SELECT PRODUCT_SUBCATEGORY_ID FROM PTBL_SUBCATEGORY WHERE PRODUCT_SUBCATEGORY_ID = 1);

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_SUBCATEGORY_ID, (SELECT MIN(TRANSACTION_DATE) FROM PTBL_TRANSACTION T WHERE PRODUCT_ID = P.PRODUCT_ID) AS MY_DATE
FROM PTBL_PRODUCT P;

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_SUBCATEGORY_ID
FROM PTBL_PRODUCT
WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM PTBL_TRANSACTION);