WITH ROW_NUMBER1 AS(
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_SUBCATEGORY_ID FROM (SELECT P.*, ROWNUM AS MY_NUM 
--, ROW_NUMBER() OVER (ORDER BY PRODUCT_ID) -- YOU CAN USE THIS METHOD ALSO
FROM PTBL_PRODUCT P)  WHERE MY_NUM = 5)
SELECT * FROM ROW_NUMBER1;

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_SUBCATEGORY_ID
FROM PTBL_PRODUCT
OFFSET 4 ROWS FETCH NEXT 1 ROW ONLY;

WITH NUMBERS AS(SELECT ROWNUM AS MY_NUM FROM OBJ$ FETCH NEXT 999 ROW ONLY)
SELECT MY_NUM, PRODUCT_NAME
FROM NUMBERS N LEFT JOIN PTBL_PRODUCT P
ON N.MY_NUM = P.PRODUCT_ID;