WITH MY_TABLE(EMPLOYEE_NUMBER, EMPLOYEE_FIRST_NAME, BOSS_NUMBER) AS(
SELECT EMPLOYEE_NUMBER, EMPLOYEE_FIRST_NAME, 0 AS BOSS_NUMBER
FROM TBL_EMPLOYEE WHERE MANAGER IS NULL
UNION ALL
SELECT E.EMPLOYEE_NUMBER, E.EMPLOYEE_FIRST_NAME, T.BOSS_NUMBER + 1 AS BOSS_NUMBER
FROM TBL_EMPLOYEE E JOIN MY_TABLE T ON E.MANAGER = T.EMPLOYEE_NUMBER)
SELECT * FROM MY_TABLE ORDER BY EMPLOYEE_NUMBER;