SELECT E.EMPLOYEE_NUMBER, EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME
    , (SELECT COUNT(*) FROM TBL_TRANSACTION T WHERE T.EMPLOYEE_NUMBER = E.EMPLOYEE_NUMBER) AS NUMBER_OF_TRANSACTION
    , (SELECT SUM(AMOUNT_NUMBER) FROM TBL_TRANSACTION T WHERE T.EMPLOYEE_NUMBER = E.EMPLOYEE_NUMBER) AS VALUE_OF_TRANSACTION
FROM TBL_EMPLOYEE E WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%' -- CORRRELATED SUBQUERY
-- YOU NEED TO PUT SOME AGGREGATION WHILE USING SUBQUERY IN SELECT STATEMENT
-- WE ONLY HAVE 1 ROW IN SUBQUERRY