UPDATE TBL_EMPLOYEE
SET MANAGER = TRUNC(((EMPLOYEE_NUMBER - 123) /10) + 123)
WHERE EMPLOYEE_NUMBER > 123;

SELECT E.EMPLOYEE_NUMBER, E.EMPLOYEE_FIRST_NAME, M.EMPLOYEE_NUMBER AS MANGER_NUMBER, M.EMPLOYEE_FIRST_NAME AS MANAGER_FIRST_NAME
FROM TBL_EMPLOYEE E LEFT JOIN TBL_EMPLOYEE M ON E.MANAGER = M.EMPLOYEE_NUMBER
ORDER BY E.EMPLOYEE_NUMBER;