SELECT T.* FROM TBL_TRANSACTION T
WHERE EXISTS (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE E WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE'Y%' AND T.EMPLOYEE_NUMBER = E.EMPLOYEE_NUMBER)
ORDER BY EMPLOYEE_NUMBER;

UPDATE TBL_TRANSACTION T
SET AMOUNT_NUMBER = AMOUNT_NUMBER / 2
WHERE EXISTS (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE E WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE'Y%' AND T.EMPLOYEE_NUMBER = E.EMPLOYEE_NUMBER);

DELETE FROM TBL_TRANSACTION T
WHERE EXISTS (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE E WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE'Y%' AND T.EMPLOYEE_NUMBER = E.EMPLOYEE_NUMBER);

ROLLBACK;