SELECT DISTINCT EMPLOYEE_NUMBER
FROM TBL_TRANSACTION
ORDER BY 1;


WITH NUMBERS AS(
        SELECT ROWNUM AS MISSING_EMPLOYEE_NUMBER FROM TBL_TRANSACTION)
, NUMBERS2 AS(
        SELECT * FROM NUMBERS WHERE MISSING_EMPLOYEE_NUMBER <= (SELECT MAX(EMPLOYEE_NUMBER) FROM TBL_EMPLOYEE))
, TRANSACTION_2021 AS(
        SELECT * FROM TBL_TRANSACTION WHERE EXTRACT(YEAR FROM DATE_OF_TRANSACTION) =  2021)
, GAPS AS(
        SELECT MISSING_EMPLOYEE_NUMBER 
        , LAG(MISSING_EMPLOYEE_NUMBER) OVER(ORDER BY MISSING_EMPLOYEE_NUMBER) AS PREVIOUS_NUMBER
        , MISSING_EMPLOYEE_NUMBER - LAG(MISSING_EMPLOYEE_NUMBER) OVER(ORDER BY MISSING_EMPLOYEE_NUMBER) AS GAP
        , CASE WHEN MISSING_EMPLOYEE_NUMBER - LAG(MISSING_EMPLOYEE_NUMBER) OVER(ORDER BY MISSING_EMPLOYEE_NUMBER) = 1 THEN 0 ELSE 1 END AS GROUP_GAP
        FROM NUMBERS2 N LEFT JOIN TBL_TRANSACTION T ON N.MISSING_EMPLOYEE_NUMBER = T.EMPLOYEE_NUMBER
        WHERE T.EMPLOYEE_NUMBER IS NULL)
, GROUPS AS(
        SELECT G.*, SUM(GROUP_GAP) OVER(ORDER BY MISSING_EMPLOYEE_NUMBER) AS THE_GROUP FROM GAPS G)

SELECT THE_GROUP, MIN(MISSING_EMPLOYEE_NUMBER) AS STARTING_EMPLOYEE, MAX(MISSING_EMPLOYEE_NUMBER) AS ENDING_EMPLOYEE FROM GROUPS
GROUP BY THE_GROUP ORDER BY THE_GROUP;