SELECT * FROM TBL_TRANSACTION
NATURAL JOIN TBL_EMPLOYEE
WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%'
ORDER BY EMPLOYEE_NUMBER;

SELECT * FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER IN
    (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE
     WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER;

SELECT * FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER NOT IN
    (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE
     WHERE UPPER(EMPLOYEE_LAST_NAME) LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER; -- OUTER JOIN

SELECT * FROM TBL_TRANSACTION
WHERE EMPLOYEE_NUMBER IN
    (SELECT EMPLOYEE_NUMBER FROM TBL_EMPLOYEE
     WHERE UPPER(EMPLOYEE_LAST_NAME) NOT LIKE 'Y%')
ORDER BY EMPLOYEE_NUMBER; -- INNER JOIN