WITH TBL_WITH_RANKING AS(
SELECT DEPARTMENT, DEPARTMENT_HEAD, EMPLOYEE_NUMBER , EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME
, ROW_NUMBER() OVER (PARTITION BY DEPARTMENT ORDER BY EMPLOYEE_NUMBER) AS MY_RANK_NUMBER
FROM TBL_DEPARTMENT NATURAL JOIN TBL_EMPLOYEE)
, TBL_WITH_TRANSACTION_2021 AS( -- ADD NEW TABLE OR NEW CODE WITH ','
SELECT * FROM TBL_TRANSACTION WHERE EXTRACT(YEAR FROM DATE_OF_TRANSACTION) = 2021)
, TBL_WITH_RANKING2 AS(
SELECT * FROM TBL_WITH_RANKING WHERE MY_RANK_NUMBER = 3)


SELECT * FROM TBL_WITH_RANKING2 NATURAL LEFT JOIN TBL_WITH_TRANSACTION_2021
WHERE MY_RANK_NUMBER <= 5
ORDER BY DEPARTMENT, EMPLOYEE_NUMBER;